version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped